       ((= (strcase BLKNAME) "FORCE")
        (progn
         (entmake)
         (entmake
          (list
           (cons 0 "BLOCK")
           (cons 2 "Force")
           (cons 70 2)
           (cons 4 "")
           (list 10 0 0 0)
          )
         )
         (entmake
          (list
           (cons 0 "CIRCLE")
           (cons 100 "AcDbEntity")
           (cons 67 0)
           (cons 8 "0")
           (cons 100 "AcDbCircle")
           (list 10 7.5 0 0)
           (cons 40 2.5)
          )
         )
         (entmake
          (list
           (cons 0 "SOLID")
           (cons 100 "AcDbEntity")
           (cons 67 0)
           (cons 8 "0")
           (cons 100 "AcDbTrace")
           (list 10 2.5 1 0)
           (list 11 0 0 0)
           (list 12 2.5 -1 0)
           (list 13 2.5 -1 0)
           (cons 39 0)
          )
         )
         (entmake
          (list
           (cons 0 "LINE")
           (cons 100 "AcDbEntity")
           (cons 67 0)
           (cons 8 "0")
           (cons 100 "AcDbLine")
           (list 10 2.5 0 0)
           (list 11 5 0 0)
          )
         )
         (entmake
          (list
           (cons 0 "ATTDEF")
           (cons 100 "AcDbEntity")
           (cons 67 0)
           (cons 8 "0")
           (cons 100 "AcDbText")
           (list 10 7.5 0 0)
           (cons 40 1)
           (cons 1 "")
           (cons 50 4.71238898)
           (cons 41 1)
           (cons 51 0)
           (cons 7 (getvar "TEXTSTYLE"))
           (cons 71 0)
           (cons 72 4)
           (list 11 7.5 0 0)
           (cons 100 "AcDbAttributeDefinition")
           (cons 3 "Force")
           (cons 2 "F")
           (cons 70 0)
           (cons 73 0)
           (cons 74 0)
          )
         )
         (entmake (list (cons 0 "ENDBLK")))
        )
       )
