       ((= (strcase BLKNAME) "SLOPE")
        (list
         (list
          (cons 0 "BLOCK")
          (cons 2 "SLOPE")
          (cons 70  2)
          (cons 4 "Slope Indicator # (Attribute)")
          (list 10 0.00000000 0.00000000 0.00000000)
         )
         (list
          (cons 0 "SOLID")
          (cons 100 "AcDbEntity")
          (cons 67 0)
          (cons 8 "0")
          (cons 100 "AcDbTrace")
          (list 10 1.50000000 -0.25000000 0.00000000)
          (list 11 2.50000000 0.00000000 0.00000000)
          (list 12 1.50000000 0.25000000 0.00000000)
          (list 13 1.50000000 0.25000000 0.00000000)
          (cons 39  0.00000000)
          (list 210 0.00000000 0.00000000 1.00000000)
         )
         (list
          (cons 0 "LINE")
          (cons 100 "AcDbEntity")
          (cons 67 0)
          (cons 8 "0")
          (cons 100 "AcDbLine")
          (list 10 -2.50000000 0.00000000 0.00000000)
          (list 11 1.50000000 0.00000000 0.00000000)
          (list 210 0.00000000 0.00000000 1.00000000)
         )
         (list
          (cons 0 "ATTDEF")
          (cons 100 "AcDbEntity")
          (cons 67 0)
          (cons 8 "0")
          (cons 100 "AcDbText")
          (list 10 0.00000000 1.20000000 0.00000000)
          (cons 40  0.75000000)
          (cons 1 "")
          (cons 50  0.00000000)
          (cons 41  1.00000000)
          (cons 51  0.00000000)
          (cons 7 "Standard")
          (cons 71 0)
          (cons 72 4)
          (list 11 0.00000000 1.20000000 0.00000000)
          (list 210 0.00000000 0.00000000 1.00000000)
          (cons 100 "AcDbAttributeDefinition")
          (cons 280 0)
          (cons 3 "Slope:")
          (cons 2 "SLOPE")
          (cons 70 0)
          (cons 73 0)
          (cons 74 0)
          (cons 280 0)
         )
         (list (cons 0 "ENDBLK"))
        )
       )
