       ((= (strcase BLKNAME) "STALBL")
        (progn
         (entmake)
         (entmake
          (list
           (cons 0 "BLOCK")
           (cons 2 "STALBL")
           (cons 70 2)
           (list 10 0 0 0)
          )
         )
         (entmake
          (list
           (cons 0 "ATTDEF")
           (cons 100 "AcDbEntity")
           (cons 67 0)
           (cons 8 "0")
           (cons 100 "AcDbText")
           (list 10 -6.92857143 -1 0)
           (cons 40 2)
           (cons 1 "100")
           (cons 50 0)
           (cons 41 1)
           (cons 51 0)
           (cons 7 (getvar "TEXTSTYLE"))
           (cons 71 0)
           (cons 72 2)
           (list 11 -1.5 0 0)
           (cons 100 "AcDbAttributeDefinition")
           (cons 3 "STAH")
           (cons 2 "STAH")
           (cons 70 0)
           (cons 73 0)
           (cons 74 2)
          )
         )
         (entmake
          (list
           (cons 0 "ATTDEF")
           (cons 100 "AcDbEntity")
           (cons 67 0)
           (cons 8 "0")
           (cons 100 "AcDbText")
           (list 10 1.5 -1 0)
           (cons 40 2)
           (cons 1 "000.000")
           (cons 50 0)
           (cons 41 1)
           (cons 51 0)
           (cons 7 (getvar "TEXTSTYLE"))
           (cons 71 0)
           (cons 72 0)
           (list 11 1.5 0 0)
           (cons 100 "AcDbAttributeDefinition")
           (cons 3 "STAL")
           (cons 2 "STAL")
           (cons 70 0)
           (cons 73 0)
           (cons 74 2)
          )
         )
         (entmake
          (list
           (cons 0 "TEXT")
           (cons 100 "AcDbEntity")
           (cons 67 0)
           (cons 8 "0")
           (cons 100 "AcDbText")
           (list 10 -1.23809524 -0.85714286 0)
           (cons 40 2)
           (cons 1 "+")
           (cons 50 0)
           (cons 41 1)
           (cons 51 0)
           (cons 7 (getvar "TEXTSTYLE"))
           (cons 71 0)
           (cons 72 4)
           (list 11 0 0 0)
           (cons 100 "AcDbText")
           (cons 73 0)
          )
         )
         (entmake (list (cons 0 "ENDBLK")))
        )
       )
