       ((= (strcase BLKNAME) "STANODELEFT")
        (list
         (list
          (cons 0 "BLOCK")
          (cons 2 "STANODELEFT")
          (cons 70  2)
          (list 10 0.00000000 0.00000000 0.00000000)
         )
         (list
          (cons 0 "LINE")
          (cons 100 "AcDbEntity")
          (cons 67 0)
          (cons 8 "0")
          (cons 100 "AcDbLine")
          (list 10 0.00000000 0.00000000 0.00000000)
          (list 11 0.00000000 40.00000000 0.00000000)
          (list 210 0.00000000 0.00000000 1.00000000)
         )
         (list
          (cons 0 "ATTDEF")
          (cons 100 "AcDbEntity")
          (cons 67 0)
          (cons 8 "0")
          (cons 100 "AcDbText")
          (list 10 0.66666667 40.00000000 0.00000000)
          (cons 40  2.00000000)
          (cons 1 "TS 100+000.000")
          (cons 50  4.71238898)
          (cons 41  1.00000000)
          (cons 51  0.00000000)
          (cons 7 "Standard")
          (cons 71 0)
          (cons 72 0)
          (list 11 0.00000000 40.00000000 0.00000000)
          (list 210 0.00000000 0.00000000 1.00000000)
          (cons 100 "AcDbAttributeDefinition")
          (cons 280 0)
          (cons 3 "Node text")
          (cons 2 "NODE")
          (cons 70 0)
          (cons 73 0)
          (cons 74 1)
          (cons 280 0)
         )
         (list (cons 0 "ENDBLK"))
        )
       )
