       ((= (strcase BLKNAME) "SUPER")
        (progn
         (entmake)
         (entmake
          (list
           (cons 0 "BLOCK")
           (cons 2 "super")
           (cons 70 2)
           (cons 4 "")
           (list 10 0 0 0)
          )
         )
         (entmake
          (list
           (cons 0 "ATTDEF")
           (cons 67 0)
           (cons 8 "0")
           (list 10 0 -1.2 0)
           (cons 40 0.75)
           (cons 1 "")
           (cons 50 0)
           (cons 41 1)
           (cons 51 0)
           (cons 7 (getvar "TEXTSTYLE"))
           (cons 71 0)
           (cons 72 4)
           (list 11 0 -1.2 0)
           (cons 3 "Left superlevation")
           (cons 2 "LEFT")
           (cons 70 0)
           (cons 73 0)
           (cons 74 0)
          )
         )
         (entmake
          (list
           (cons 0 "POINT")
           (cons 67 0)
           (cons 8 "0")
           (list 10 0 0 0)
           (cons 50 0)
          )
         )
         (entmake
          (list
           (cons 0 "ATTDEF")
           (cons 67 0)
           (cons 8 "0")
           (list 10 0 1.2 0)
           (cons 40 0.75)
           (cons 1 "")
           (cons 50 0)
           (cons 41 1)
           (cons 51 0)
           (cons 7 (getvar "TEXTSTYLE"))
           (cons 71 0)
           (cons 72 4)
           (list 11 0 1.2 0)
           (cons 3 "Right superlevation")
           (cons 2 "RIGHT")
           (cons 70 0)
           (cons 73 0)
           (cons 74 0)
          )
         )
         (entmake (list (cons 0 "ENDBLK")))
        )
       )
