       ((= (strcase BLKNAME) "SURVEYSPOT")
        (progn
         (entmake)
         (entmake
          (list
           (cons 0 "BLOCK")
           (cons 2 "surveyspot")
           (cons 70 2)
           (list 10 0 0 0)
          )
         )
         (entmake
          (list
           (cons 0 "POINT")
           (cons 100 "AcDbEntity")
           (cons 67 0)
           (cons 8 "0")
           (cons 100 "AcDbPoint")
           (list 10 0 0 0)
           (cons 50 0)
          )
         )
         (entmake
          (list
           (cons 0 "ATTDEF")
           (cons 100 "AcDbEntity")
           (cons 67 0)
           (cons 8 "0")
           (cons 100 "AcDbText")
           (list 10 1 1.21428571 0)
           (cons 40 1)
           (cons 1 "")
           (cons 50 0)
           (cons 41 0.75)
           (cons 51 0)
           (cons 7 (getvar "TEXTSTYLE"))
           (cons 71 0)
           (cons 72 0)
           (list 11 1 1.71428571 0)
           (cons 100 "AcDbAttributeDefinition")
           (cons 3 "Point Number")
           (cons 2 "PNTNO")
           (cons 70 0)
           (cons 73 0)
           (cons 74 2)
          )
         )
         (entmake
          (list
           (cons 0 "ATTDEF")
           (cons 100 "AcDbEntity")
           (cons 67 0)
           (cons 8 "0")
           (cons 100 "AcDbText")
           (list 10 1 -0.5 0)
           (cons 40 1)
           (cons 1 "")
           (cons 50 0)
           (cons 41 0.75)
           (cons 51 0)
           (cons 7 (getvar "TEXTSTYLE"))
           (cons 71 0)
           (cons 72 0)
           (list 11 1 0 0)
           (cons 100 "AcDbAttributeDefinition")
           (cons 3 "ELEVATION")
           (cons 2 "ELEV")
           (cons 70 0)
           (cons 73 0)
           (cons 74 2)
          )
         )
         (entmake
          (list
           (cons 0 "ATTDEF")
           (cons 100 "AcDbEntity")
           (cons 67 0)
           (cons 8 "0")
           (cons 100 "AcDbText")
           (list 10 1 -2.21428571 0)
           (cons 40 1)
           (cons 1 "")
           (cons 50 0)
           (cons 41 0.75)
           (cons 51 0)
           (cons 7 (getvar "TEXTSTYLE"))
           (cons 71 0)
           (cons 72 0)
           (list 11 1 -1.71428571 0)
           (cons 100 "AcDbAttributeDefinition")
           (cons 3 "Description")
           (cons 2 "DESC")
           (cons 70 0)
           (cons 73 0)
           (cons 74 2)
          )
         )
         (entmake (list (cons 0 "ENDBLK")))
        )
       )
